# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioConfigData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AudioConfigData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x41udioConfigData.proto\x12\x17gb.xxy.trial.proto.data\"L\n\x0b\x41udioConfig\x12\x13\n\x0bsample_rate\x18\x01 \x02(\r\x12\x11\n\tbit_depth\x18\x02 \x02(\r\x12\x15\n\rchannel_count\x18\x03 \x02(\r')
)




_AUDIOCONFIG = _descriptor.Descriptor(
  name='AudioConfig',
  full_name='gb.xxy.trial.proto.data.AudioConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='gb.xxy.trial.proto.data.AudioConfig.sample_rate', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bit_depth', full_name='gb.xxy.trial.proto.data.AudioConfig.bit_depth', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_count', full_name='gb.xxy.trial.proto.data.AudioConfig.channel_count', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['AudioConfig'] = _AUDIOCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioConfig = _reflection.GeneratedProtocolMessageType('AudioConfig', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOCONFIG,
  '__module__' : 'AudioConfigData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.AudioConfig)
  })
_sym_db.RegisterMessage(AudioConfig)


# @@protoc_insertion_point(module_scope)
