# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioFocusStateEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AudioFocusStateEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x41udioFocusStateEnum.proto\x12\x18gb.xxy.trial.proto.enums\"\xb4\x01\n\x0f\x41udioFocusState\"\xa0\x01\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04GAIN\x10\x01\x12\x12\n\x0eGAIN_TRANSIENT\x10\x02\x12\x08\n\x04LOSS\x10\x03\x12\x1b\n\x17LOSS_TRANSIENT_CAN_DUCK\x10\x04\x12\x12\n\x0eLOSS_TRANSIENT\x10\x05\x12\x13\n\x0fGAIN_MEDIA_ONLY\x10\x06\x12 \n\x1cGAIN_TRANSIENT_GUIDANCE_ONLY\x10\x07')
)



_AUDIOFOCUSSTATE_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.AudioFocusState.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAIN_TRANSIENT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOSS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOSS_TRANSIENT_CAN_DUCK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOSS_TRANSIENT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAIN_MEDIA_ONLY', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAIN_TRANSIENT_GUIDANCE_ONLY', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=76,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_AUDIOFOCUSSTATE_ENUM)


_AUDIOFOCUSSTATE = _descriptor.Descriptor(
  name='AudioFocusState',
  full_name='gb.xxy.trial.proto.enums.AudioFocusState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUDIOFOCUSSTATE_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=236,
)

_AUDIOFOCUSSTATE_ENUM.containing_type = _AUDIOFOCUSSTATE
DESCRIPTOR.message_types_by_name['AudioFocusState'] = _AUDIOFOCUSSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioFocusState = _reflection.GeneratedProtocolMessageType('AudioFocusState', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOFOCUSSTATE,
  '__module__' : 'AudioFocusStateEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.AudioFocusState)
  })
_sym_db.RegisterMessage(AudioFocusState)


# @@protoc_insertion_point(module_scope)
