# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioFocusRequestMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import AudioFocusTypeEnum_pb2 as AudioFocusTypeEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AudioFocusRequestMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x41udioFocusRequestMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a\x18\x41udioFocusTypeEnum.proto\"\\\n\x11\x41udioFocusRequest\x12G\n\x10\x61udio_focus_type\x18\x01 \x02(\x0e\x32-.gb.xxy.trial.proto.enums.AudioFocusType.Enum')
  ,
  dependencies=[AudioFocusTypeEnum__pb2.DESCRIPTOR,])




_AUDIOFOCUSREQUEST = _descriptor.Descriptor(
  name='AudioFocusRequest',
  full_name='gb.xxy.trial.proto.messages.AudioFocusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_focus_type', full_name='gb.xxy.trial.proto.messages.AudioFocusRequest.audio_focus_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=181,
)

_AUDIOFOCUSREQUEST.fields_by_name['audio_focus_type'].enum_type = AudioFocusTypeEnum__pb2._AUDIOFOCUSTYPE_ENUM
DESCRIPTOR.message_types_by_name['AudioFocusRequest'] = _AUDIOFOCUSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioFocusRequest = _reflection.GeneratedProtocolMessageType('AudioFocusRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOFOCUSREQUEST,
  '__module__' : 'AudioFocusRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.AudioFocusRequest)
  })
_sym_db.RegisterMessage(AudioFocusRequest)


# @@protoc_insertion_point(module_scope)
