# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioFocusTypeEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AudioFocusTypeEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x41udioFocusTypeEnum.proto\x12\x18gb.xxy.trial.proto.enums\"\\\n\x0e\x41udioFocusType\"J\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04GAIN\x10\x01\x12\x12\n\x0eGAIN_TRANSIENT\x10\x02\x12\r\n\tGAIN_NAVI\x10\x03\x12\x0b\n\x07RELEASE\x10\x04')
)



_AUDIOFOCUSTYPE_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.AudioFocusType.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAIN_TRANSIENT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAIN_NAVI', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELEASE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=72,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_AUDIOFOCUSTYPE_ENUM)


_AUDIOFOCUSTYPE = _descriptor.Descriptor(
  name='AudioFocusType',
  full_name='gb.xxy.trial.proto.enums.AudioFocusType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUDIOFOCUSTYPE_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=146,
)

_AUDIOFOCUSTYPE_ENUM.containing_type = _AUDIOFOCUSTYPE
DESCRIPTOR.message_types_by_name['AudioFocusType'] = _AUDIOFOCUSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioFocusType = _reflection.GeneratedProtocolMessageType('AudioFocusType', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOFOCUSTYPE,
  '__module__' : 'AudioFocusTypeEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.AudioFocusType)
  })
_sym_db.RegisterMessage(AudioFocusType)


# @@protoc_insertion_point(module_scope)
