# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioFocusResponseMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import AudioFocusStateEnum_pb2 as AudioFocusStateEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AudioFocusResponseMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1f\x41udioFocusResponseMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a\x19\x41udioFocusStateEnum.proto\"_\n\x12\x41udioFocusResponse\x12I\n\x11\x61udio_focus_state\x18\x01 \x02(\x0e\x32..gb.xxy.trial.proto.enums.AudioFocusState.Enum')
  ,
  dependencies=[AudioFocusStateEnum__pb2.DESCRIPTOR,])




_AUDIOFOCUSRESPONSE = _descriptor.Descriptor(
  name='AudioFocusResponse',
  full_name='gb.xxy.trial.proto.messages.AudioFocusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_focus_state', full_name='gb.xxy.trial.proto.messages.AudioFocusResponse.audio_focus_state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=186,
)

_AUDIOFOCUSRESPONSE.fields_by_name['audio_focus_state'].enum_type = AudioFocusStateEnum__pb2._AUDIOFOCUSSTATE_ENUM
DESCRIPTOR.message_types_by_name['AudioFocusResponse'] = _AUDIOFOCUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioFocusResponse = _reflection.GeneratedProtocolMessageType('AudioFocusResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOFOCUSRESPONSE,
  '__module__' : 'AudioFocusResponseMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.AudioFocusResponse)
  })
_sym_db.RegisterMessage(AudioFocusResponse)


# @@protoc_insertion_point(module_scope)
