# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AVChannelSetupResponseMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import AVChannelSetupStatusEnum_pb2 as AVChannelSetupStatusEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AVChannelSetupResponseMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n#AVChannelSetupResponseMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a\x1e\x41VChannelSetupStatusEnum.proto\"\x89\x01\n\x16\x41VChannelSetupResponse\x12I\n\x0cmedia_status\x18\x01 \x02(\x0e\x32\x33.gb.xxy.trial.proto.enums.AVChannelSetupStatus.Enum\x12\x13\n\x0bmax_unacked\x18\x02 \x02(\r\x12\x0f\n\x07\x63onfigs\x18\x03 \x03(\r')
  ,
  dependencies=[AVChannelSetupStatusEnum__pb2.DESCRIPTOR,])




_AVCHANNELSETUPRESPONSE = _descriptor.Descriptor(
  name='AVChannelSetupResponse',
  full_name='gb.xxy.trial.proto.messages.AVChannelSetupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='media_status', full_name='gb.xxy.trial.proto.messages.AVChannelSetupResponse.media_status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_unacked', full_name='gb.xxy.trial.proto.messages.AVChannelSetupResponse.max_unacked', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='configs', full_name='gb.xxy.trial.proto.messages.AVChannelSetupResponse.configs', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=238,
)

_AVCHANNELSETUPRESPONSE.fields_by_name['media_status'].enum_type = AVChannelSetupStatusEnum__pb2._AVCHANNELSETUPSTATUS_ENUM
DESCRIPTOR.message_types_by_name['AVChannelSetupResponse'] = _AVCHANNELSETUPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AVChannelSetupResponse = _reflection.GeneratedProtocolMessageType('AVChannelSetupResponse', (_message.Message,), {
  'DESCRIPTOR' : _AVCHANNELSETUPRESPONSE,
  '__module__' : 'AVChannelSetupResponseMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.AVChannelSetupResponse)
  })
_sym_db.RegisterMessage(AVChannelSetupResponse)


# @@protoc_insertion_point(module_scope)
