# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AVChannelSetupStatusEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AVChannelSetupStatusEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x41VChannelSetupStatusEnum.proto\x12\x18gb.xxy.trial.proto.enums\":\n\x14\x41VChannelSetupStatus\"\"\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x12\x06\n\x02OK\x10\x02')
)



_AVCHANNELSETUPSTATUS_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.AVChannelSetupStatus.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=84,
  serialized_end=118,
)
_sym_db.RegisterEnumDescriptor(_AVCHANNELSETUPSTATUS_ENUM)


_AVCHANNELSETUPSTATUS = _descriptor.Descriptor(
  name='AVChannelSetupStatus',
  full_name='gb.xxy.trial.proto.enums.AVChannelSetupStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AVCHANNELSETUPSTATUS_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=118,
)

_AVCHANNELSETUPSTATUS_ENUM.containing_type = _AVCHANNELSETUPSTATUS
DESCRIPTOR.message_types_by_name['AVChannelSetupStatus'] = _AVCHANNELSETUPSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AVChannelSetupStatus = _reflection.GeneratedProtocolMessageType('AVChannelSetupStatus', (_message.Message,), {
  'DESCRIPTOR' : _AVCHANNELSETUPSTATUS,
  '__module__' : 'AVChannelSetupStatusEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.AVChannelSetupStatus)
  })
_sym_db.RegisterMessage(AVChannelSetupStatus)


# @@protoc_insertion_point(module_scope)
