# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AVChannelData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import AVStreamTypeEnum_pb2 as AVStreamTypeEnum__pb2
from . import AudioTypeEnum_pb2 as AudioTypeEnum__pb2
from . import AudioConfigData_pb2 as AudioConfigData__pb2
from . import VideoConfigData_pb2 as VideoConfigData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AVChannelData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x41VChannelData.proto\x12\x17gb.xxy.trial.proto.data\x1a\x16\x41VStreamTypeEnum.proto\x1a\x13\x41udioTypeEnum.proto\x1a\x15\x41udioConfigData.proto\x1a\x15VideoConfigData.proto\"\xa6\x02\n\tAVChannel\x12@\n\x0bstream_type\x18\x01 \x02(\x0e\x32+.gb.xxy.trial.proto.enums.AVStreamType.Enum\x12<\n\naudio_type\x18\x02 \x01(\x0e\x32(.gb.xxy.trial.proto.enums.AudioType.Enum\x12;\n\raudio_configs\x18\x03 \x03(\x0b\x32$.gb.xxy.trial.proto.data.AudioConfig\x12;\n\rvideo_configs\x18\x04 \x03(\x0b\x32$.gb.xxy.trial.proto.data.VideoConfig\x12\x1f\n\x17\x61vailable_while_in_call\x18\x05 \x01(\x08')
  ,
  dependencies=[AVStreamTypeEnum__pb2.DESCRIPTOR,AudioTypeEnum__pb2.DESCRIPTOR,AudioConfigData__pb2.DESCRIPTOR,VideoConfigData__pb2.DESCRIPTOR,])




_AVCHANNEL = _descriptor.Descriptor(
  name='AVChannel',
  full_name='gb.xxy.trial.proto.data.AVChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_type', full_name='gb.xxy.trial.proto.data.AVChannel.stream_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_type', full_name='gb.xxy.trial.proto.data.AVChannel.audio_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_configs', full_name='gb.xxy.trial.proto.data.AVChannel.audio_configs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_configs', full_name='gb.xxy.trial.proto.data.AVChannel.video_configs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='available_while_in_call', full_name='gb.xxy.trial.proto.data.AVChannel.available_while_in_call', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=434,
)

_AVCHANNEL.fields_by_name['stream_type'].enum_type = AVStreamTypeEnum__pb2._AVSTREAMTYPE_ENUM
_AVCHANNEL.fields_by_name['audio_type'].enum_type = AudioTypeEnum__pb2._AUDIOTYPE_ENUM
_AVCHANNEL.fields_by_name['audio_configs'].message_type = AudioConfigData__pb2._AUDIOCONFIG
_AVCHANNEL.fields_by_name['video_configs'].message_type = VideoConfigData__pb2._VIDEOCONFIG
DESCRIPTOR.message_types_by_name['AVChannel'] = _AVCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AVChannel = _reflection.GeneratedProtocolMessageType('AVChannel', (_message.Message,), {
  'DESCRIPTOR' : _AVCHANNEL,
  '__module__' : 'AVChannelData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.AVChannel)
  })
_sym_db.RegisterMessage(AVChannel)


# @@protoc_insertion_point(module_scope)
