# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AVInputOpenRequestMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AVInputOpenRequestMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1f\x41VInputOpenRequestMessage.proto\x12\x1bgb.xxy.trial.proto.messages\"P\n\x12\x41VInputOpenRequest\x12\x0c\n\x04open\x18\x01 \x02(\x08\x12\x0b\n\x03\x61nc\x18\x02 \x02(\x08\x12\n\n\x02\x65\x63\x18\x03 \x02(\x08\x12\x13\n\x0bmax_unacked\x18\x04 \x02(\x05')
)




_AVINPUTOPENREQUEST = _descriptor.Descriptor(
  name='AVInputOpenRequest',
  full_name='gb.xxy.trial.proto.messages.AVInputOpenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open', full_name='gb.xxy.trial.proto.messages.AVInputOpenRequest.open', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anc', full_name='gb.xxy.trial.proto.messages.AVInputOpenRequest.anc', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ec', full_name='gb.xxy.trial.proto.messages.AVInputOpenRequest.ec', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_unacked', full_name='gb.xxy.trial.proto.messages.AVInputOpenRequest.max_unacked', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['AVInputOpenRequest'] = _AVINPUTOPENREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AVInputOpenRequest = _reflection.GeneratedProtocolMessageType('AVInputOpenRequest', (_message.Message,), {
  'DESCRIPTOR' : _AVINPUTOPENREQUEST,
  '__module__' : 'AVInputOpenRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.AVInputOpenRequest)
  })
_sym_db.RegisterMessage(AVInputOpenRequest)


# @@protoc_insertion_point(module_scope)
