# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BindingRequestMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BindingRequestMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x42indingRequestMessage.proto\x12\x1bgb.xxy.trial.proto.messages\"$\n\x0e\x42indingRequest\x12\x12\n\nscan_codes\x18\x01 \x03(\x05')
)




_BINDINGREQUEST = _descriptor.Descriptor(
  name='BindingRequest',
  full_name='gb.xxy.trial.proto.messages.BindingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scan_codes', full_name='gb.xxy.trial.proto.messages.BindingRequest.scan_codes', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['BindingRequest'] = _BINDINGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BindingRequest = _reflection.GeneratedProtocolMessageType('BindingRequest', (_message.Message,), {
  'DESCRIPTOR' : _BINDINGREQUEST,
  '__module__' : 'BindingRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.BindingRequest)
  })
_sym_db.RegisterMessage(BindingRequest)


# @@protoc_insertion_point(module_scope)
