# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BluetoothChannelData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import BluetoothPairingMethodEnum_pb2 as BluetoothPairingMethodEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BluetoothChannelData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x42luetoothChannelData.proto\x12\x17gb.xxy.trial.proto.data\x1a BluetoothPairingMethodEnum.proto\"\x85\x01\n\x10\x42luetoothChannel\x12\x17\n\x0f\x61\x64\x61pter_address\x18\x01 \x02(\t\x12X\n\x19supported_pairing_methods\x18\x02 \x03(\x0e\x32\x35.gb.xxy.trial.proto.enums.BluetoothPairingMethod.Enum')
  ,
  dependencies=[BluetoothPairingMethodEnum__pb2.DESCRIPTOR,])




_BLUETOOTHCHANNEL = _descriptor.Descriptor(
  name='BluetoothChannel',
  full_name='gb.xxy.trial.proto.data.BluetoothChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adapter_address', full_name='gb.xxy.trial.proto.data.BluetoothChannel.adapter_address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supported_pairing_methods', full_name='gb.xxy.trial.proto.data.BluetoothChannel.supported_pairing_methods', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=223,
)

_BLUETOOTHCHANNEL.fields_by_name['supported_pairing_methods'].enum_type = BluetoothPairingMethodEnum__pb2._BLUETOOTHPAIRINGMETHOD_ENUM
DESCRIPTOR.message_types_by_name['BluetoothChannel'] = _BLUETOOTHCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BluetoothChannel = _reflection.GeneratedProtocolMessageType('BluetoothChannel', (_message.Message,), {
  'DESCRIPTOR' : _BLUETOOTHCHANNEL,
  '__module__' : 'BluetoothChannelData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.BluetoothChannel)
  })
_sym_db.RegisterMessage(BluetoothChannel)


# @@protoc_insertion_point(module_scope)
