# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BluetoothPairingRequestMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import BluetoothPairingMethodEnum_pb2 as BluetoothPairingMethodEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BluetoothPairingRequestMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n$BluetoothPairingRequestMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a BluetoothPairingMethodEnum.proto\"\x7f\n\x17\x42luetoothPairingRequest\x12\x15\n\rphone_address\x18\x01 \x02(\t\x12M\n\x0epairing_method\x18\x02 \x02(\x0e\x32\x35.gb.xxy.trial.proto.enums.BluetoothPairingMethod.Enum')
  ,
  dependencies=[BluetoothPairingMethodEnum__pb2.DESCRIPTOR,])




_BLUETOOTHPAIRINGREQUEST = _descriptor.Descriptor(
  name='BluetoothPairingRequest',
  full_name='gb.xxy.trial.proto.messages.BluetoothPairingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone_address', full_name='gb.xxy.trial.proto.messages.BluetoothPairingRequest.phone_address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pairing_method', full_name='gb.xxy.trial.proto.messages.BluetoothPairingRequest.pairing_method', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=230,
)

_BLUETOOTHPAIRINGREQUEST.fields_by_name['pairing_method'].enum_type = BluetoothPairingMethodEnum__pb2._BLUETOOTHPAIRINGMETHOD_ENUM
DESCRIPTOR.message_types_by_name['BluetoothPairingRequest'] = _BLUETOOTHPAIRINGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BluetoothPairingRequest = _reflection.GeneratedProtocolMessageType('BluetoothPairingRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLUETOOTHPAIRINGREQUEST,
  '__module__' : 'BluetoothPairingRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.BluetoothPairingRequest)
  })
_sym_db.RegisterMessage(BluetoothPairingRequest)


# @@protoc_insertion_point(module_scope)
