# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BluetoothChannelMessageIdsEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BluetoothChannelMessageIdsEnum.proto',
  package='gb.xxy.trial.proto.ids',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n$BluetoothChannelMessageIdsEnum.proto\x12\x16gb.xxy.trial.proto.ids\"k\n\x17\x42luetoothChannelMessage\"P\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x15\n\x0fPAIRING_REQUEST\x10\x81\x80\x02\x12\x16\n\x10PAIRING_RESPONSE\x10\x82\x80\x02\x12\x0f\n\tAUTH_DATA\x10\x83\x80\x02')
)



_BLUETOOTHCHANNELMESSAGE_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.ids.BluetoothChannelMessage.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAIRING_REQUEST', index=1, number=32769,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAIRING_RESPONSE', index=2, number=32770,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTH_DATA', index=3, number=32771,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=91,
  serialized_end=171,
)
_sym_db.RegisterEnumDescriptor(_BLUETOOTHCHANNELMESSAGE_ENUM)


_BLUETOOTHCHANNELMESSAGE = _descriptor.Descriptor(
  name='BluetoothChannelMessage',
  full_name='gb.xxy.trial.proto.ids.BluetoothChannelMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BLUETOOTHCHANNELMESSAGE_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=171,
)

_BLUETOOTHCHANNELMESSAGE_ENUM.containing_type = _BLUETOOTHCHANNELMESSAGE
DESCRIPTOR.message_types_by_name['BluetoothChannelMessage'] = _BLUETOOTHCHANNELMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BluetoothChannelMessage = _reflection.GeneratedProtocolMessageType('BluetoothChannelMessage', (_message.Message,), {
  'DESCRIPTOR' : _BLUETOOTHCHANNELMESSAGE,
  '__module__' : 'BluetoothChannelMessageIdsEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.ids.BluetoothChannelMessage)
  })
_sym_db.RegisterMessage(BluetoothChannelMessage)


# @@protoc_insertion_point(module_scope)
