# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ButtonEventsData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ButtonEventData_pb2 as ButtonEventData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ButtonEventsData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x42uttonEventsData.proto\x12\x17gb.xxy.trial.proto.data\x1a\x15\x42uttonEventData.proto\"K\n\x0c\x42uttonEvents\x12;\n\rbutton_events\x18\x01 \x03(\x0b\x32$.gb.xxy.trial.proto.data.ButtonEvent')
  ,
  dependencies=[ButtonEventData__pb2.DESCRIPTOR,])




_BUTTONEVENTS = _descriptor.Descriptor(
  name='ButtonEvents',
  full_name='gb.xxy.trial.proto.data.ButtonEvents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button_events', full_name='gb.xxy.trial.proto.data.ButtonEvents.button_events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=149,
)

_BUTTONEVENTS.fields_by_name['button_events'].message_type = ButtonEventData__pb2._BUTTONEVENT
DESCRIPTOR.message_types_by_name['ButtonEvents'] = _BUTTONEVENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ButtonEvents = _reflection.GeneratedProtocolMessageType('ButtonEvents', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONEVENTS,
  '__module__' : 'ButtonEventsData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.ButtonEvents)
  })
_sym_db.RegisterMessage(ButtonEvents)


# @@protoc_insertion_point(module_scope)
