# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ButtonEventData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ButtonEventData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x42uttonEventData.proto\x12\x17gb.xxy.trial.proto.data\"V\n\x0b\x42uttonEvent\x12\x11\n\tscan_code\x18\x01 \x02(\r\x12\x12\n\nis_pressed\x18\x02 \x02(\x08\x12\x0c\n\x04meta\x18\x03 \x01(\r\x12\x12\n\nlong_press\x18\x04 \x01(\x08')
)




_BUTTONEVENT = _descriptor.Descriptor(
  name='ButtonEvent',
  full_name='gb.xxy.trial.proto.data.ButtonEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scan_code', full_name='gb.xxy.trial.proto.data.ButtonEvent.scan_code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_pressed', full_name='gb.xxy.trial.proto.data.ButtonEvent.is_pressed', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='gb.xxy.trial.proto.data.ButtonEvent.meta', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_press', full_name='gb.xxy.trial.proto.data.ButtonEvent.long_press', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['ButtonEvent'] = _BUTTONEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ButtonEvent = _reflection.GeneratedProtocolMessageType('ButtonEvent', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONEVENT,
  '__module__' : 'ButtonEventData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.ButtonEvent)
  })
_sym_db.RegisterMessage(ButtonEvent)


# @@protoc_insertion_point(module_scope)
