# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ButtonCodeEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ButtonCodeEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x42uttonCodeEnum.proto\x12\x18gb.xxy.trial.proto.enums\"\xfa\x01\n\nButtonCode\"\xeb\x01\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0cMICROPHONE_2\x10\x01\x12\x08\n\x04MENU\x10\x02\x12\x08\n\x04HOME\x10\x03\x12\x08\n\x04\x42\x41\x43K\x10\x04\x12\t\n\x05PHONE\x10\x05\x12\x0c\n\x08\x43\x41LL_END\x10\x06\x12\x06\n\x02UP\x10\x13\x12\x08\n\x04\x44OWN\x10\x14\x12\x08\n\x04LEFT\x10\x15\x12\t\n\x05RIGHT\x10\x16\x12\t\n\x05\x45NTER\x10\x17\x12\x10\n\x0cMICROPHONE_1\x10T\x12\x0f\n\x0bTOGGLE_PLAY\x10U\x12\x08\n\x04NEXT\x10W\x12\x08\n\x04PREV\x10X\x12\x08\n\x04PLAY\x10~\x12\t\n\x05PAUSE\x10\x7f\x12\x12\n\x0cSCROLL_WHEEL\x10\x80\x80\x04')
)



_BUTTONCODE_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.ButtonCode.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICROPHONE_2', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MENU', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHONE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALL_END', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UP', index=7, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=8, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=9, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=10, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER', index=11, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICROPHONE_1', index=12, number=84,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOGGLE_PLAY', index=13, number=85,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEXT', index=14, number=87,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREV', index=15, number=88,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAY', index=16, number=126,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAUSE', index=17, number=127,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCROLL_WHEEL', index=18, number=65536,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=66,
  serialized_end=301,
)
_sym_db.RegisterEnumDescriptor(_BUTTONCODE_ENUM)


_BUTTONCODE = _descriptor.Descriptor(
  name='ButtonCode',
  full_name='gb.xxy.trial.proto.enums.ButtonCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUTTONCODE_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=301,
)

_BUTTONCODE_ENUM.containing_type = _BUTTONCODE
DESCRIPTOR.message_types_by_name['ButtonCode'] = _BUTTONCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ButtonCode = _reflection.GeneratedProtocolMessageType('ButtonCode', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONCODE,
  '__module__' : 'ButtonCodeEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.ButtonCode)
  })
_sym_db.RegisterMessage(ButtonCode)


# @@protoc_insertion_point(module_scope)
