# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelOpenRequestMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChannelOpenRequestMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1f\x43hannelOpenRequestMessage.proto\x12\x1bgb.xxy.trial.proto.messages\":\n\x12\x43hannelOpenRequest\x12\x10\n\x08priority\x18\x01 \x02(\x05\x12\x12\n\nchannel_id\x18\x02 \x02(\x05')
)




_CHANNELOPENREQUEST = _descriptor.Descriptor(
  name='ChannelOpenRequest',
  full_name='gb.xxy.trial.proto.messages.ChannelOpenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='gb.xxy.trial.proto.messages.ChannelOpenRequest.priority', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='gb.xxy.trial.proto.messages.ChannelOpenRequest.channel_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['ChannelOpenRequest'] = _CHANNELOPENREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChannelOpenRequest = _reflection.GeneratedProtocolMessageType('ChannelOpenRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELOPENREQUEST,
  '__module__' : 'ChannelOpenRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.ChannelOpenRequest)
  })
_sym_db.RegisterMessage(ChannelOpenRequest)


# @@protoc_insertion_point(module_scope)
