# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ControlMessageIdsEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ControlMessageIdsEnum.proto',
  package='gb.xxy.trial.proto.ids',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x43ontrolMessageIdsEnum.proto\x12\x16gb.xxy.trial.proto.ids\"\xc5\x03\n\x0e\x43ontrolMessage\"\xb2\x03\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x13\n\x0fVERSION_REQUEST\x10\x01\x12\x14\n\x10VERSION_RESPONSE\x10\x02\x12\x11\n\rSSL_HANDSHAKE\x10\x03\x12\x11\n\rAUTH_COMPLETE\x10\x04\x12\x1d\n\x19SERVICE_DISCOVERY_REQUEST\x10\x05\x12\x1e\n\x1aSERVICE_DISCOVERY_RESPONSE\x10\x06\x12\x18\n\x14\x43HANNEL_OPEN_REQUEST\x10\x07\x12\x19\n\x15\x43HANNEL_OPEN_RESPONSE\x10\x08\x12\x10\n\x0cPING_REQUEST\x10\x0b\x12\x11\n\rPING_RESPONSE\x10\x0c\x12\x1c\n\x18NAVIGATION_FOCUS_REQUEST\x10\r\x12\x1d\n\x19NAVIGATION_FOCUS_RESPONSE\x10\x0e\x12\x14\n\x10SHUTDOWN_REQUEST\x10\x0f\x12\x15\n\x11SHUTDOWN_RESPONSE\x10\x10\x12\x19\n\x15VOICE_SESSION_REQUEST\x10\x11\x12\x17\n\x13\x41UDIO_FOCUS_REQUEST\x10\x12\x12\x18\n\x14\x41UDIO_FOCUS_RESPONSE\x10\x13')
)



_CONTROLMESSAGE_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.ids.ControlMessage.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_REQUEST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_RESPONSE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SSL_HANDSHAKE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTH_COMPLETE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_DISCOVERY_REQUEST', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_DISCOVERY_RESPONSE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHANNEL_OPEN_REQUEST', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHANNEL_OPEN_RESPONSE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING_REQUEST', index=9, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING_RESPONSE', index=10, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAVIGATION_FOCUS_REQUEST', index=11, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAVIGATION_FOCUS_RESPONSE', index=12, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_REQUEST', index=13, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_RESPONSE', index=14, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOICE_SESSION_REQUEST', index=15, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUDIO_FOCUS_REQUEST', index=16, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUDIO_FOCUS_RESPONSE', index=17, number=19,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=75,
  serialized_end=509,
)
_sym_db.RegisterEnumDescriptor(_CONTROLMESSAGE_ENUM)


_CONTROLMESSAGE = _descriptor.Descriptor(
  name='ControlMessage',
  full_name='gb.xxy.trial.proto.ids.ControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLMESSAGE_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=509,
)

_CONTROLMESSAGE_ENUM.containing_type = _CONTROLMESSAGE
DESCRIPTOR.message_types_by_name['ControlMessage'] = _CONTROLMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlMessage = _reflection.GeneratedProtocolMessageType('ControlMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLMESSAGE,
  '__module__' : 'ControlMessageIdsEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.ids.ControlMessage)
  })
_sym_db.RegisterMessage(ControlMessage)


# @@protoc_insertion_point(module_scope)
