# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DiagnosticsData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DiagnosticsData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x44iagnosticsData.proto\x12\x17gb.xxy.trial.proto.data\"\"\n\x0b\x44iagnostics\x12\x13\n\x0b\x64iagnostics\x18\x01 \x02(\x0c')
)




_DIAGNOSTICS = _descriptor.Descriptor(
  name='Diagnostics',
  full_name='gb.xxy.trial.proto.data.Diagnostics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='diagnostics', full_name='gb.xxy.trial.proto.data.Diagnostics.diagnostics', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Diagnostics'] = _DIAGNOSTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Diagnostics = _reflection.GeneratedProtocolMessageType('Diagnostics', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSTICS,
  '__module__' : 'DiagnosticsData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.Diagnostics)
  })
_sym_db.RegisterMessage(Diagnostics)


# @@protoc_insertion_point(module_scope)
