# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DoorData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DoorData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x44oorData.proto\x12\x17gb.xxy.trial.proto.data\"?\n\x04\x44oor\x12\x11\n\thood_open\x18\x01 \x02(\x08\x12\x11\n\tboot_open\x18\x02 \x02(\x08\x12\x11\n\tdoor_open\x18\x03 \x03(\x08')
)




_DOOR = _descriptor.Descriptor(
  name='Door',
  full_name='gb.xxy.trial.proto.data.Door',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hood_open', full_name='gb.xxy.trial.proto.data.Door.hood_open', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boot_open', full_name='gb.xxy.trial.proto.data.Door.boot_open', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='door_open', full_name='gb.xxy.trial.proto.data.Door.door_open', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['Door'] = _DOOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Door = _reflection.GeneratedProtocolMessageType('Door', (_message.Message,), {
  'DESCRIPTOR' : _DOOR,
  '__module__' : 'DoorData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.Door)
  })
_sym_db.RegisterMessage(Door)


# @@protoc_insertion_point(module_scope)
