# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DrivingStatusEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DrivingStatusEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x44rivingStatusEnum.proto\x12\x18gb.xxy.trial.proto.enums\"\x9f\x01\n\rDrivingStatus\"\x8d\x01\n\x04\x45num\x12\x10\n\x0cUNRESTRICTED\x10\x00\x12\x0c\n\x08NO_VIDEO\x10\x01\x12\x15\n\x11NO_KEYBOARD_INPUT\x10\x02\x12\x12\n\x0eNO_VOICE_INPUT\x10\x04\x12\r\n\tNO_CONFIG\x10\x08\x12\x15\n\x11LIMIT_MESSAGE_LEN\x10\x10\x12\x14\n\x10\x46ULLY_RESTRICTED\x10\x1f')
)



_DRIVINGSTATUS_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.DrivingStatus.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNRESTRICTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_VIDEO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_KEYBOARD_INPUT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_VOICE_INPUT', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_CONFIG', index=4, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIMIT_MESSAGE_LEN', index=5, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FULLY_RESTRICTED', index=6, number=31,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=72,
  serialized_end=213,
)
_sym_db.RegisterEnumDescriptor(_DRIVINGSTATUS_ENUM)


_DRIVINGSTATUS = _descriptor.Descriptor(
  name='DrivingStatus',
  full_name='gb.xxy.trial.proto.enums.DrivingStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRIVINGSTATUS_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=213,
)

_DRIVINGSTATUS_ENUM.containing_type = _DRIVINGSTATUS
DESCRIPTOR.message_types_by_name['DrivingStatus'] = _DRIVINGSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DrivingStatus = _reflection.GeneratedProtocolMessageType('DrivingStatus', (_message.Message,), {
  'DESCRIPTOR' : _DRIVINGSTATUS,
  '__module__' : 'DrivingStatusEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.DrivingStatus)
  })
_sym_db.RegisterMessage(DrivingStatus)


# @@protoc_insertion_point(module_scope)
