# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GearEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GearEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0eGearEnum.proto\x12\x18gb.xxy.trial.proto.enums\"\xb1\x01\n\x04Gear\"\xa8\x01\n\x04\x45num\x12\x0b\n\x07NEUTRAL\x10\x00\x12\t\n\x05\x46IRST\x10\x01\x12\n\n\x06SECOND\x10\x02\x12\t\n\x05THIRD\x10\x03\x12\n\n\x06\x46OURTH\x10\x04\x12\t\n\x05\x46IFTH\x10\x05\x12\t\n\x05SIXTH\x10\x06\x12\x0b\n\x07SEVENTH\x10\x07\x12\n\n\x06\x45IGHTH\x10\x08\x12\t\n\x05NINTH\x10\t\x12\t\n\x05TENTH\x10\n\x12\t\n\x05\x44RIVE\x10\x64\x12\x08\n\x04PARK\x10\x65\x12\x0b\n\x07REVERSE\x10\x66')
)



_GEAR_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.Gear.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEUTRAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIRST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECOND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THIRD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FOURTH', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIFTH', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIXTH', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEVENTH', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EIGHTH', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NINTH', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TENTH', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRIVE', index=11, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARK', index=12, number=101,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVERSE', index=13, number=102,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=54,
  serialized_end=222,
)
_sym_db.RegisterEnumDescriptor(_GEAR_ENUM)


_GEAR = _descriptor.Descriptor(
  name='Gear',
  full_name='gb.xxy.trial.proto.enums.Gear',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GEAR_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=222,
)

_GEAR_ENUM.containing_type = _GEAR
DESCRIPTOR.message_types_by_name['Gear'] = _GEAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gear = _reflection.GeneratedProtocolMessageType('Gear', (_message.Message,), {
  'DESCRIPTOR' : _GEAR,
  '__module__' : 'GearEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.Gear)
  })
_sym_db.RegisterMessage(Gear)


# @@protoc_insertion_point(module_scope)
