# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GPSLocationData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GPSLocationData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15GPSLocationData.proto\x12\x17gb.xxy.trial.proto.data\"\x89\x01\n\x0bGPSLocation\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x10\n\x08latitude\x18\x02 \x02(\x05\x12\x11\n\tlongitude\x18\x03 \x02(\x05\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x02(\r\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x05\x12\r\n\x05speed\x18\x06 \x01(\x05\x12\x0f\n\x07\x62\x65\x61ring\x18\x07 \x01(\x05')
)




_GPSLOCATION = _descriptor.Descriptor(
  name='GPSLocation',
  full_name='gb.xxy.trial.proto.data.GPSLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='gb.xxy.trial.proto.data.GPSLocation.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='gb.xxy.trial.proto.data.GPSLocation.latitude', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='gb.xxy.trial.proto.data.GPSLocation.longitude', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='gb.xxy.trial.proto.data.GPSLocation.accuracy', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='gb.xxy.trial.proto.data.GPSLocation.altitude', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='gb.xxy.trial.proto.data.GPSLocation.speed', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bearing', full_name='gb.xxy.trial.proto.data.GPSLocation.bearing', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['GPSLocation'] = _GPSLOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GPSLocation = _reflection.GeneratedProtocolMessageType('GPSLocation', (_message.Message,), {
  'DESCRIPTOR' : _GPSLOCATION,
  '__module__' : 'GPSLocationData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.GPSLocation)
  })
_sym_db.RegisterMessage(GPSLocation)


# @@protoc_insertion_point(module_scope)
