# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HeadlightStatusEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HeadlightStatusEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19HeadlightStatusEnum.proto\x12\x18gb.xxy.trial.proto.enums\"M\n\x0fHeadlightStatus\":\n\x04\x45num\x12\x0b\n\x07STATE_0\x10\x00\x12\x0b\n\x07STATE_1\x10\x01\x12\x0b\n\x07STATE_2\x10\x02\x12\x0b\n\x07STATE_3\x10\x03')
)



_HEADLIGHTSTATUS_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.HeadlightStatus.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATE_0', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_3', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=74,
  serialized_end=132,
)
_sym_db.RegisterEnumDescriptor(_HEADLIGHTSTATUS_ENUM)


_HEADLIGHTSTATUS = _descriptor.Descriptor(
  name='HeadlightStatus',
  full_name='gb.xxy.trial.proto.enums.HeadlightStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HEADLIGHTSTATUS_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=132,
)

_HEADLIGHTSTATUS_ENUM.containing_type = _HEADLIGHTSTATUS
DESCRIPTOR.message_types_by_name['HeadlightStatus'] = _HEADLIGHTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeadlightStatus = _reflection.GeneratedProtocolMessageType('HeadlightStatus', (_message.Message,), {
  'DESCRIPTOR' : _HEADLIGHTSTATUS,
  '__module__' : 'HeadlightStatusEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.HeadlightStatus)
  })
_sym_db.RegisterMessage(HeadlightStatus)


# @@protoc_insertion_point(module_scope)
