# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HVACData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HVACData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0eHVACData.proto\x12\x17gb.xxy.trial.proto.data\"?\n\x04HVAC\x12\x1a\n\x12target_temperature\x18\x01 \x02(\x05\x12\x1b\n\x13\x63urrent_temperature\x18\x02 \x02(\x05')
)




_HVAC = _descriptor.Descriptor(
  name='HVAC',
  full_name='gb.xxy.trial.proto.data.HVAC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_temperature', full_name='gb.xxy.trial.proto.data.HVAC.target_temperature', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_temperature', full_name='gb.xxy.trial.proto.data.HVAC.current_temperature', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['HVAC'] = _HVAC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HVAC = _reflection.GeneratedProtocolMessageType('HVAC', (_message.Message,), {
  'DESCRIPTOR' : _HVAC,
  '__module__' : 'HVACData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.HVAC)
  })
_sym_db.RegisterMessage(HVAC)


# @@protoc_insertion_point(module_scope)
