# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InputChannelData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import TouchConfigData_pb2 as TouchConfigData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='InputChannelData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16InputChannelData.proto\x12\x17gb.xxy.trial.proto.data\x1a\x15TouchConfigData.proto\"\xad\x01\n\x0cInputChannel\x12\x1a\n\x12supported_keycodes\x18\x01 \x03(\r\x12\x41\n\x13touch_screen_config\x18\x02 \x01(\x0b\x32$.gb.xxy.trial.proto.data.TouchConfig\x12>\n\x10touch_pad_config\x18\x03 \x01(\x0b\x32$.gb.xxy.trial.proto.data.TouchConfig')
  ,
  dependencies=[TouchConfigData__pb2.DESCRIPTOR,])




_INPUTCHANNEL = _descriptor.Descriptor(
  name='InputChannel',
  full_name='gb.xxy.trial.proto.data.InputChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='supported_keycodes', full_name='gb.xxy.trial.proto.data.InputChannel.supported_keycodes', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='touch_screen_config', full_name='gb.xxy.trial.proto.data.InputChannel.touch_screen_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='touch_pad_config', full_name='gb.xxy.trial.proto.data.InputChannel.touch_pad_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=248,
)

_INPUTCHANNEL.fields_by_name['touch_screen_config'].message_type = TouchConfigData__pb2._TOUCHCONFIG
_INPUTCHANNEL.fields_by_name['touch_pad_config'].message_type = TouchConfigData__pb2._TOUCHCONFIG
DESCRIPTOR.message_types_by_name['InputChannel'] = _INPUTCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputChannel = _reflection.GeneratedProtocolMessageType('InputChannel', (_message.Message,), {
  'DESCRIPTOR' : _INPUTCHANNEL,
  '__module__' : 'InputChannelData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.InputChannel)
  })
_sym_db.RegisterMessage(InputChannel)


# @@protoc_insertion_point(module_scope)
