# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InputEventIndicationMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import TouchEventData_pb2 as TouchEventData__pb2
from . import ButtonEventsData_pb2 as ButtonEventsData__pb2
from . import AbsoluteInputEventsData_pb2 as AbsoluteInputEventsData__pb2
from . import RelativeInputEventsData_pb2 as RelativeInputEventsData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='InputEventIndicationMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n!InputEventIndicationMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a\x14TouchEventData.proto\x1a\x16\x42uttonEventsData.proto\x1a\x1d\x41\x62soluteInputEventsData.proto\x1a\x1dRelativeInputEventsData.proto\"\xce\x02\n\x14InputEventIndication\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x14\n\x0c\x64isp_channel\x18\x02 \x01(\x05\x12\x38\n\x0btouch_event\x18\x03 \x01(\x0b\x32#.gb.xxy.trial.proto.data.TouchEvent\x12;\n\x0c\x62utton_event\x18\x04 \x01(\x0b\x32%.gb.xxy.trial.proto.data.ButtonEvents\x12J\n\x14\x61\x62solute_input_event\x18\x05 \x01(\x0b\x32,.gb.xxy.trial.proto.data.AbsoluteInputEvents\x12J\n\x14relative_input_event\x18\x06 \x01(\x0b\x32,.gb.xxy.trial.proto.data.RelativeInputEvents')
  ,
  dependencies=[TouchEventData__pb2.DESCRIPTOR,ButtonEventsData__pb2.DESCRIPTOR,AbsoluteInputEventsData__pb2.DESCRIPTOR,RelativeInputEventsData__pb2.DESCRIPTOR,])




_INPUTEVENTINDICATION = _descriptor.Descriptor(
  name='InputEventIndication',
  full_name='gb.xxy.trial.proto.messages.InputEventIndication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='gb.xxy.trial.proto.messages.InputEventIndication.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disp_channel', full_name='gb.xxy.trial.proto.messages.InputEventIndication.disp_channel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='touch_event', full_name='gb.xxy.trial.proto.messages.InputEventIndication.touch_event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button_event', full_name='gb.xxy.trial.proto.messages.InputEventIndication.button_event', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='absolute_input_event', full_name='gb.xxy.trial.proto.messages.InputEventIndication.absolute_input_event', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relative_input_event', full_name='gb.xxy.trial.proto.messages.InputEventIndication.relative_input_event', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=509,
)

_INPUTEVENTINDICATION.fields_by_name['touch_event'].message_type = TouchEventData__pb2._TOUCHEVENT
_INPUTEVENTINDICATION.fields_by_name['button_event'].message_type = ButtonEventsData__pb2._BUTTONEVENTS
_INPUTEVENTINDICATION.fields_by_name['absolute_input_event'].message_type = AbsoluteInputEventsData__pb2._ABSOLUTEINPUTEVENTS
_INPUTEVENTINDICATION.fields_by_name['relative_input_event'].message_type = RelativeInputEventsData__pb2._RELATIVEINPUTEVENTS
DESCRIPTOR.message_types_by_name['InputEventIndication'] = _INPUTEVENTINDICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputEventIndication = _reflection.GeneratedProtocolMessageType('InputEventIndication', (_message.Message,), {
  'DESCRIPTOR' : _INPUTEVENTINDICATION,
  '__module__' : 'InputEventIndicationMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.InputEventIndication)
  })
_sym_db.RegisterMessage(InputEventIndication)


# @@protoc_insertion_point(module_scope)
