# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MediaChannelData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MediaChannelData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16MediaChannelData.proto\x12\x17gb.xxy.trial.proto.data\"\x12\n\x10MediaInfoChannel')
)




_MEDIAINFOCHANNEL = _descriptor.Descriptor(
  name='MediaInfoChannel',
  full_name='gb.xxy.trial.proto.data.MediaInfoChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['MediaInfoChannel'] = _MEDIAINFOCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MediaInfoChannel = _reflection.GeneratedProtocolMessageType('MediaInfoChannel', (_message.Message,), {
  'DESCRIPTOR' : _MEDIAINFOCHANNEL,
  '__module__' : 'MediaChannelData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.MediaInfoChannel)
  })
_sym_db.RegisterMessage(MediaInfoChannel)


# @@protoc_insertion_point(module_scope)
