# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NavigationChannelData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import NavigationImageOptionsData_pb2 as NavigationImageOptionsData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NavigationChannelData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1bNavigationChannelData.proto\x12\x17gb.xxy.trial.proto.data\x1a NavigationImageOptionsData.proto\"\x86\x01\n\x11NavigationChannel\x12\x1b\n\x13minimum_interval_ms\x18\x01 \x02(\r\x12\x0c\n\x04type\x18\x02 \x02(\r\x12\x46\n\rimage_options\x18\x03 \x02(\x0b\x32/.gb.xxy.trial.proto.data.NavigationImageOptions')
  ,
  dependencies=[NavigationImageOptionsData__pb2.DESCRIPTOR,])




_NAVIGATIONCHANNEL = _descriptor.Descriptor(
  name='NavigationChannel',
  full_name='gb.xxy.trial.proto.data.NavigationChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minimum_interval_ms', full_name='gb.xxy.trial.proto.data.NavigationChannel.minimum_interval_ms', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='gb.xxy.trial.proto.data.NavigationChannel.type', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_options', full_name='gb.xxy.trial.proto.data.NavigationChannel.image_options', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=225,
)

_NAVIGATIONCHANNEL.fields_by_name['image_options'].message_type = NavigationImageOptionsData__pb2._NAVIGATIONIMAGEOPTIONS
DESCRIPTOR.message_types_by_name['NavigationChannel'] = _NAVIGATIONCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NavigationChannel = _reflection.GeneratedProtocolMessageType('NavigationChannel', (_message.Message,), {
  'DESCRIPTOR' : _NAVIGATIONCHANNEL,
  '__module__' : 'NavigationChannelData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.NavigationChannel)
  })
_sym_db.RegisterMessage(NavigationChannel)


# @@protoc_insertion_point(module_scope)
