# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NightModeData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NightModeData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13NightModeData.proto\x12\x17gb.xxy.trial.proto.data\"\x1d\n\tNightMode\x12\x10\n\x08is_night\x18\x01 \x02(\x08')
)




_NIGHTMODE = _descriptor.Descriptor(
  name='NightMode',
  full_name='gb.xxy.trial.proto.data.NightMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_night', full_name='gb.xxy.trial.proto.data.NightMode.is_night', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['NightMode'] = _NIGHTMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NightMode = _reflection.GeneratedProtocolMessageType('NightMode', (_message.Message,), {
  'DESCRIPTOR' : _NIGHTMODE,
  '__module__' : 'NightModeData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.NightMode)
  })
_sym_db.RegisterMessage(NightMode)


# @@protoc_insertion_point(module_scope)
