# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OdometerData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OdometerData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12OdometerData.proto\x12\x17gb.xxy.trial.proto.data\"7\n\x08Odometer\x12\x15\n\rtotal_mileage\x18\x01 \x02(\x05\x12\x14\n\x0ctrip_mileage\x18\x02 \x02(\x05')
)




_ODOMETER = _descriptor.Descriptor(
  name='Odometer',
  full_name='gb.xxy.trial.proto.data.Odometer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_mileage', full_name='gb.xxy.trial.proto.data.Odometer.total_mileage', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trip_mileage', full_name='gb.xxy.trial.proto.data.Odometer.trip_mileage', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['Odometer'] = _ODOMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Odometer = _reflection.GeneratedProtocolMessageType('Odometer', (_message.Message,), {
  'DESCRIPTOR' : _ODOMETER,
  '__module__' : 'OdometerData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.Odometer)
  })
_sym_db.RegisterMessage(Odometer)


# @@protoc_insertion_point(module_scope)
