# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ParkingBrakeData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ParkingBrakeData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16ParkingBrakeData.proto\x12\x17gb.xxy.trial.proto.data\"%\n\x0cParkingBrake\x12\x15\n\rparking_brake\x18\x01 \x02(\x08')
)




_PARKINGBRAKE = _descriptor.Descriptor(
  name='ParkingBrake',
  full_name='gb.xxy.trial.proto.data.ParkingBrake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parking_brake', full_name='gb.xxy.trial.proto.data.ParkingBrake.parking_brake', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['ParkingBrake'] = _PARKINGBRAKE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParkingBrake = _reflection.GeneratedProtocolMessageType('ParkingBrake', (_message.Message,), {
  'DESCRIPTOR' : _PARKINGBRAKE,
  '__module__' : 'ParkingBrakeData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.ParkingBrake)
  })
_sym_db.RegisterMessage(ParkingBrake)


# @@protoc_insertion_point(module_scope)
