# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RelativeInputEventsData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import RelativeInputEventData_pb2 as RelativeInputEventData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RelativeInputEventsData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1dRelativeInputEventsData.proto\x12\x17gb.xxy.trial.proto.data\x1a\x1cRelativeInputEventData.proto\"a\n\x13RelativeInputEvents\x12J\n\x15relative_input_events\x18\x01 \x03(\x0b\x32+.gb.xxy.trial.proto.data.RelativeInputEvent')
  ,
  dependencies=[RelativeInputEventData__pb2.DESCRIPTOR,])




_RELATIVEINPUTEVENTS = _descriptor.Descriptor(
  name='RelativeInputEvents',
  full_name='gb.xxy.trial.proto.data.RelativeInputEvents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='relative_input_events', full_name='gb.xxy.trial.proto.data.RelativeInputEvents.relative_input_events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=185,
)

_RELATIVEINPUTEVENTS.fields_by_name['relative_input_events'].message_type = RelativeInputEventData__pb2._RELATIVEINPUTEVENT
DESCRIPTOR.message_types_by_name['RelativeInputEvents'] = _RELATIVEINPUTEVENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RelativeInputEvents = _reflection.GeneratedProtocolMessageType('RelativeInputEvents', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVEINPUTEVENTS,
  '__module__' : 'RelativeInputEventsData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.RelativeInputEvents)
  })
_sym_db.RegisterMessage(RelativeInputEvents)


# @@protoc_insertion_point(module_scope)
