# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RelativeInputEventData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RelativeInputEventData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1cRelativeInputEventData.proto\x12\x17gb.xxy.trial.proto.data\"6\n\x12RelativeInputEvent\x12\x11\n\tscan_code\x18\x01 \x02(\r\x12\r\n\x05\x64\x65lta\x18\x02 \x02(\x05')
)




_RELATIVEINPUTEVENT = _descriptor.Descriptor(
  name='RelativeInputEvent',
  full_name='gb.xxy.trial.proto.data.RelativeInputEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scan_code', full_name='gb.xxy.trial.proto.data.RelativeInputEvent.scan_code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delta', full_name='gb.xxy.trial.proto.data.RelativeInputEvent.delta', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['RelativeInputEvent'] = _RELATIVEINPUTEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RelativeInputEvent = _reflection.GeneratedProtocolMessageType('RelativeInputEvent', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVEINPUTEVENT,
  '__module__' : 'RelativeInputEventData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.RelativeInputEvent)
  })
_sym_db.RegisterMessage(RelativeInputEvent)


# @@protoc_insertion_point(module_scope)
