# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RPMData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RPMData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rRPMData.proto\x12\x17gb.xxy.trial.proto.data\"\x12\n\x03RPM\x12\x0b\n\x03rpm\x18\x01 \x02(\x05')
)




_RPM = _descriptor.Descriptor(
  name='RPM',
  full_name='gb.xxy.trial.proto.data.RPM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpm', full_name='gb.xxy.trial.proto.data.RPM.rpm', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['RPM'] = _RPM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPM = _reflection.GeneratedProtocolMessageType('RPM', (_message.Message,), {
  'DESCRIPTOR' : _RPM,
  '__module__' : 'RPMData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.RPM)
  })
_sym_db.RegisterMessage(RPM)


# @@protoc_insertion_point(module_scope)
