# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorTypeEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorTypeEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14SensorTypeEnum.proto\x12\x18gb.xxy.trial.proto.enums\"\xbc\x02\n\nSensorType\"\xad\x02\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08LOCATION\x10\x01\x12\x0b\n\x07\x43OMPASS\x10\x02\x12\r\n\tCAR_SPEED\x10\x03\x12\x07\n\x03RPM\x10\x04\x12\x0c\n\x08ODOMETER\x10\x05\x12\x0e\n\nFUEL_LEVEL\x10\x06\x12\x11\n\rPARKING_BRAKE\x10\x07\x12\x08\n\x04GEAR\x10\x08\x12\x0f\n\x0b\x44IAGNOSTICS\x10\t\x12\x0e\n\nNIGHT_DATA\x10\n\x12\x0f\n\x0b\x45NVIRONMENT\x10\x0b\x12\x08\n\x04HVAC\x10\x0c\x12\x12\n\x0e\x44RIVING_STATUS\x10\r\x12\x11\n\rDEAD_RECONING\x10\x0e\x12\r\n\tPASSENGER\x10\x0f\x12\x08\n\x04\x44OOR\x10\x10\x12\t\n\x05LIGHT\x10\x11\x12\x08\n\x04TIRE\x10\x12\x12\t\n\x05\x41\x43\x43\x45L\x10\x13\x12\x08\n\x04GYRO\x10\x14\x12\x07\n\x03GPS\x10\x15')
)



_SENSORTYPE_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.SensorType.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCATION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPASS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAR_SPEED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RPM', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ODOMETER', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUEL_LEVEL', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARKING_BRAKE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSTICS', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NIGHT_DATA', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENVIRONMENT', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HVAC', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRIVING_STATUS', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEAD_RECONING', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASSENGER', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOOR', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIGHT', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIRE', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEL', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GYRO', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS', index=21, number=21,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=66,
  serialized_end=367,
)
_sym_db.RegisterEnumDescriptor(_SENSORTYPE_ENUM)


_SENSORTYPE = _descriptor.Descriptor(
  name='SensorType',
  full_name='gb.xxy.trial.proto.enums.SensorType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSORTYPE_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=367,
)

_SENSORTYPE_ENUM.containing_type = _SENSORTYPE
DESCRIPTOR.message_types_by_name['SensorType'] = _SENSORTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorType = _reflection.GeneratedProtocolMessageType('SensorType', (_message.Message,), {
  'DESCRIPTOR' : _SENSORTYPE,
  '__module__' : 'SensorTypeEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.SensorType)
  })
_sym_db.RegisterMessage(SensorType)


# @@protoc_insertion_point(module_scope)
