# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorChannelData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SensorData_pb2 as SensorData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorChannelData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17SensorChannelData.proto\x12\x17gb.xxy.trial.proto.data\x1a\x10SensorData.proto\"A\n\rSensorChannel\x12\x30\n\x07sensors\x18\x01 \x03(\x0b\x32\x1f.gb.xxy.trial.proto.data.Sensor')
  ,
  dependencies=[SensorData__pb2.DESCRIPTOR,])




_SENSORCHANNEL = _descriptor.Descriptor(
  name='SensorChannel',
  full_name='gb.xxy.trial.proto.data.SensorChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensors', full_name='gb.xxy.trial.proto.data.SensorChannel.sensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=135,
)

_SENSORCHANNEL.fields_by_name['sensors'].message_type = SensorData__pb2._SENSOR
DESCRIPTOR.message_types_by_name['SensorChannel'] = _SENSORCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorChannel = _reflection.GeneratedProtocolMessageType('SensorChannel', (_message.Message,), {
  'DESCRIPTOR' : _SENSORCHANNEL,
  '__module__' : 'SensorChannelData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.SensorChannel)
  })
_sym_db.RegisterMessage(SensorChannel)


# @@protoc_insertion_point(module_scope)
