# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SensorTypeEnum_pb2 as SensorTypeEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10SensorData.proto\x12\x17gb.xxy.trial.proto.data\x1a\x14SensorTypeEnum.proto\"A\n\x06Sensor\x12\x37\n\x04type\x18\x01 \x02(\x0e\x32).gb.xxy.trial.proto.enums.SensorType.Enum')
  ,
  dependencies=[SensorTypeEnum__pb2.DESCRIPTOR,])




_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='gb.xxy.trial.proto.data.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='gb.xxy.trial.proto.data.Sensor.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=132,
)

_SENSOR.fields_by_name['type'].enum_type = SensorTypeEnum__pb2._SENSORTYPE_ENUM
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR,
  '__module__' : 'SensorData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.Sensor)
  })
_sym_db.RegisterMessage(Sensor)


# @@protoc_insertion_point(module_scope)
