# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorChannelMessageIdsEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorChannelMessageIdsEnum.proto',
  package='gb.xxy.trial.proto.ids',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n!SensorChannelMessageIdsEnum.proto\x12\x16gb.xxy.trial.proto.ids\"\x80\x01\n\x14SensorChannelMessage\"h\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x1a\n\x14SENSOR_START_REQUEST\x10\x81\x80\x02\x12\x1b\n\x15SENSOR_START_RESPONSE\x10\x82\x80\x02\x12\x1d\n\x17SENSOR_EVENT_INDICATION\x10\x83\x80\x02')
)



_SENSORCHANNELMESSAGE_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.ids.SensorChannelMessage.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_START_REQUEST', index=1, number=32769,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_START_RESPONSE', index=2, number=32770,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_EVENT_INDICATION', index=3, number=32771,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=86,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_SENSORCHANNELMESSAGE_ENUM)


_SENSORCHANNELMESSAGE = _descriptor.Descriptor(
  name='SensorChannelMessage',
  full_name='gb.xxy.trial.proto.ids.SensorChannelMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSORCHANNELMESSAGE_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=190,
)

_SENSORCHANNELMESSAGE_ENUM.containing_type = _SENSORCHANNELMESSAGE
DESCRIPTOR.message_types_by_name['SensorChannelMessage'] = _SENSORCHANNELMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorChannelMessage = _reflection.GeneratedProtocolMessageType('SensorChannelMessage', (_message.Message,), {
  'DESCRIPTOR' : _SENSORCHANNELMESSAGE,
  '__module__' : 'SensorChannelMessageIdsEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.ids.SensorChannelMessage)
  })
_sym_db.RegisterMessage(SensorChannelMessage)


# @@protoc_insertion_point(module_scope)
