# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServiceDiscoveryRequestMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServiceDiscoveryRequestMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n$ServiceDiscoveryRequestMessage.proto\x12\x1bgb.xxy.trial.proto.messages\"D\n\x17ServiceDiscoveryRequest\x12\x13\n\x0b\x64\x65vice_name\x18\x04 \x02(\t\x12\x14\n\x0c\x64\x65vice_brand\x18\x05 \x02(\t')
)




_SERVICEDISCOVERYREQUEST = _descriptor.Descriptor(
  name='ServiceDiscoveryRequest',
  full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_name', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryRequest.device_name', index=0,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_brand', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryRequest.device_brand', index=1,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['ServiceDiscoveryRequest'] = _SERVICEDISCOVERYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceDiscoveryRequest = _reflection.GeneratedProtocolMessageType('ServiceDiscoveryRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEDISCOVERYREQUEST,
  '__module__' : 'ServiceDiscoveryRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.ServiceDiscoveryRequest)
  })
_sym_db.RegisterMessage(ServiceDiscoveryRequest)


# @@protoc_insertion_point(module_scope)
