# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServiceDiscoveryResponseMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ChannelDescriptorData_pb2 as ChannelDescriptorData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServiceDiscoveryResponseMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n%ServiceDiscoveryResponseMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a\x1b\x43hannelDescriptorData.proto\"\xe4\x02\n\x18ServiceDiscoveryResponse\x12<\n\x08\x63hannels\x18\x01 \x03(\x0b\x32*.gb.xxy.trial.proto.data.ChannelDescriptor\x12\x16\n\x0ehead_unit_name\x18\x02 \x02(\t\x12\x11\n\tcar_model\x18\x03 \x02(\t\x12\x10\n\x08\x63\x61r_year\x18\x04 \x02(\t\x12\x12\n\ncar_serial\x18\x05 \x02(\t\x12\x1f\n\x17left_hand_drive_vehicle\x18\x06 \x02(\x08\x12\x1d\n\x15headunit_manufacturer\x18\x07 \x02(\t\x12\x16\n\x0eheadunit_model\x18\x08 \x02(\t\x12\x10\n\x08sw_build\x18\t \x02(\t\x12\x12\n\nsw_version\x18\n \x02(\t\x12\'\n\x1f\x63\x61n_play_native_media_during_vr\x18\x0b \x02(\x08\x12\x12\n\nhide_clock\x18\x0c \x01(\x08')
  ,
  dependencies=[ChannelDescriptorData__pb2.DESCRIPTOR,])




_SERVICEDISCOVERYRESPONSE = _descriptor.Descriptor(
  name='ServiceDiscoveryResponse',
  full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.channels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='head_unit_name', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.head_unit_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car_model', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.car_model', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car_year', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.car_year', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car_serial', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.car_serial', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_hand_drive_vehicle', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.left_hand_drive_vehicle', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headunit_manufacturer', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.headunit_manufacturer', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headunit_model', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.headunit_model', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sw_build', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.sw_build', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sw_version', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.sw_version', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_play_native_media_during_vr', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.can_play_native_media_during_vr', index=10,
      number=11, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hide_clock', full_name='gb.xxy.trial.proto.messages.ServiceDiscoveryResponse.hide_clock', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=456,
)

_SERVICEDISCOVERYRESPONSE.fields_by_name['channels'].message_type = ChannelDescriptorData__pb2._CHANNELDESCRIPTOR
DESCRIPTOR.message_types_by_name['ServiceDiscoveryResponse'] = _SERVICEDISCOVERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceDiscoveryResponse = _reflection.GeneratedProtocolMessageType('ServiceDiscoveryResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEDISCOVERYRESPONSE,
  '__module__' : 'ServiceDiscoveryResponseMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.ServiceDiscoveryResponse)
  })
_sym_db.RegisterMessage(ServiceDiscoveryResponse)


# @@protoc_insertion_point(module_scope)
