# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShutdownRequestMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ShutdownReasonEnum_pb2 as ShutdownReasonEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ShutdownRequestMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1cShutdownRequestMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a\x18ShutdownReasonEnum.proto\"P\n\x0fShutdownRequest\x12=\n\x06reason\x18\x01 \x02(\x0e\x32-.gb.xxy.trial.proto.enums.ShutdownReason.Enum')
  ,
  dependencies=[ShutdownReasonEnum__pb2.DESCRIPTOR,])




_SHUTDOWNREQUEST = _descriptor.Descriptor(
  name='ShutdownRequest',
  full_name='gb.xxy.trial.proto.messages.ShutdownRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='gb.xxy.trial.proto.messages.ShutdownRequest.reason', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=167,
)

_SHUTDOWNREQUEST.fields_by_name['reason'].enum_type = ShutdownReasonEnum__pb2._SHUTDOWNREASON_ENUM
DESCRIPTOR.message_types_by_name['ShutdownRequest'] = _SHUTDOWNREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShutdownRequest = _reflection.GeneratedProtocolMessageType('ShutdownRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNREQUEST,
  '__module__' : 'ShutdownRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.ShutdownRequest)
  })
_sym_db.RegisterMessage(ShutdownRequest)


# @@protoc_insertion_point(module_scope)
