# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShutdownReasonEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ShutdownReasonEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18ShutdownReasonEnum.proto\x12\x18gb.xxy.trial.proto.enums\",\n\x0eShutdownReason\"\x1a\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04QUIT\x10\x01')
)



_SHUTDOWNREASON_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.ShutdownReason.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUIT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=72,
  serialized_end=98,
)
_sym_db.RegisterEnumDescriptor(_SHUTDOWNREASON_ENUM)


_SHUTDOWNREASON = _descriptor.Descriptor(
  name='ShutdownReason',
  full_name='gb.xxy.trial.proto.enums.ShutdownReason',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SHUTDOWNREASON_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=98,
)

_SHUTDOWNREASON_ENUM.containing_type = _SHUTDOWNREASON
DESCRIPTOR.message_types_by_name['ShutdownReason'] = _SHUTDOWNREASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShutdownReason = _reflection.GeneratedProtocolMessageType('ShutdownReason', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNREASON,
  '__module__' : 'ShutdownReasonEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.ShutdownReason)
  })
_sym_db.RegisterMessage(ShutdownReason)


# @@protoc_insertion_point(module_scope)
