# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpeedData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpeedData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fSpeedData.proto\x12\x17gb.xxy.trial.proto.data\"H\n\x05Speed\x12\r\n\x05speed\x18\x01 \x02(\x05\x12\x16\n\x0e\x63ruise_engaged\x18\x02 \x01(\x08\x12\x18\n\x10\x63ruise_set_speed\x18\x03 \x01(\x08')
)




_SPEED = _descriptor.Descriptor(
  name='Speed',
  full_name='gb.xxy.trial.proto.data.Speed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='gb.xxy.trial.proto.data.Speed.speed', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cruise_engaged', full_name='gb.xxy.trial.proto.data.Speed.cruise_engaged', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cruise_set_speed', full_name='gb.xxy.trial.proto.data.Speed.cruise_set_speed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['Speed'] = _SPEED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Speed = _reflection.GeneratedProtocolMessageType('Speed', (_message.Message,), {
  'DESCRIPTOR' : _SPEED,
  '__module__' : 'SpeedData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.Speed)
  })
_sym_db.RegisterMessage(Speed)


# @@protoc_insertion_point(module_scope)
