# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SteeringWheelData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SteeringWheelData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17SteeringWheelData.proto\x12\x17gb.xxy.trial.proto.data\"<\n\rSteeringWheel\x12\x16\n\x0esteering_angle\x18\x01 \x02(\x05\x12\x13\n\x0bwheel_speed\x18\x02 \x02(\x05')
)




_STEERINGWHEEL = _descriptor.Descriptor(
  name='SteeringWheel',
  full_name='gb.xxy.trial.proto.data.SteeringWheel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steering_angle', full_name='gb.xxy.trial.proto.data.SteeringWheel.steering_angle', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheel_speed', full_name='gb.xxy.trial.proto.data.SteeringWheel.wheel_speed', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['SteeringWheel'] = _STEERINGWHEEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SteeringWheel = _reflection.GeneratedProtocolMessageType('SteeringWheel', (_message.Message,), {
  'DESCRIPTOR' : _STEERINGWHEEL,
  '__module__' : 'SteeringWheelData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.SteeringWheel)
  })
_sym_db.RegisterMessage(SteeringWheel)


# @@protoc_insertion_point(module_scope)
