# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TouchActionEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TouchActionEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15TouchActionEnum.proto\x12\x18gb.xxy.trial.proto.enums\"Y\n\x0bTouchAction\"J\n\x04\x45num\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01\x12\x08\n\x04\x44RAG\x10\x02\x12\x10\n\x0cPOINTER_DOWN\x10\x05\x12\x0e\n\nPOINTER_UP\x10\x06')
)



_TOUCHACTION_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.TouchAction.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELEASE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POINTER_DOWN', index=3, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POINTER_UP', index=4, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=66,
  serialized_end=140,
)
_sym_db.RegisterEnumDescriptor(_TOUCHACTION_ENUM)


_TOUCHACTION = _descriptor.Descriptor(
  name='TouchAction',
  full_name='gb.xxy.trial.proto.enums.TouchAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TOUCHACTION_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=140,
)

_TOUCHACTION_ENUM.containing_type = _TOUCHACTION
DESCRIPTOR.message_types_by_name['TouchAction'] = _TOUCHACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TouchAction = _reflection.GeneratedProtocolMessageType('TouchAction', (_message.Message,), {
  'DESCRIPTOR' : _TOUCHACTION,
  '__module__' : 'TouchActionEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.TouchAction)
  })
_sym_db.RegisterMessage(TouchAction)


# @@protoc_insertion_point(module_scope)
