# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VendorExtensionChannelData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VendorExtensionChannelData.proto',
  package='gb.xxy.trial.proto.data',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n VendorExtensionChannelData.proto\x12\x17gb.xxy.trial.proto.data\"P\n\x16VendorExtensionChannel\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1a\n\x12package_white_list\x18\x02 \x03(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c')
)




_VENDOREXTENSIONCHANNEL = _descriptor.Descriptor(
  name='VendorExtensionChannel',
  full_name='gb.xxy.trial.proto.data.VendorExtensionChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gb.xxy.trial.proto.data.VendorExtensionChannel.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_white_list', full_name='gb.xxy.trial.proto.data.VendorExtensionChannel.package_white_list', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='gb.xxy.trial.proto.data.VendorExtensionChannel.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['VendorExtensionChannel'] = _VENDOREXTENSIONCHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VendorExtensionChannel = _reflection.GeneratedProtocolMessageType('VendorExtensionChannel', (_message.Message,), {
  'DESCRIPTOR' : _VENDOREXTENSIONCHANNEL,
  '__module__' : 'VendorExtensionChannelData_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.data.VendorExtensionChannel)
  })
_sym_db.RegisterMessage(VendorExtensionChannel)


# @@protoc_insertion_point(module_scope)
