# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VideoFocusRequestMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import VideoFocusModeEnum_pb2 as VideoFocusModeEnum__pb2
from . import VideoFocusReasonEnum_pb2 as VideoFocusReasonEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='VideoFocusRequestMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1eVideoFocusRequestMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a\x18VideoFocusModeEnum.proto\x1a\x1aVideoFocusReasonEnum.proto\"\xb1\x01\n\x11VideoFocusRequest\x12\x12\n\ndisp_index\x18\x01 \x02(\x05\x12\x41\n\nfocus_mode\x18\x02 \x02(\x0e\x32-.gb.xxy.trial.proto.enums.VideoFocusMode.Enum\x12\x45\n\x0c\x66ocus_reason\x18\x03 \x02(\x0e\x32/.gb.xxy.trial.proto.enums.VideoFocusReason.Enum')
  ,
  dependencies=[VideoFocusModeEnum__pb2.DESCRIPTOR,VideoFocusReasonEnum__pb2.DESCRIPTOR,])




_VIDEOFOCUSREQUEST = _descriptor.Descriptor(
  name='VideoFocusRequest',
  full_name='gb.xxy.trial.proto.messages.VideoFocusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disp_index', full_name='gb.xxy.trial.proto.messages.VideoFocusRequest.disp_index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='focus_mode', full_name='gb.xxy.trial.proto.messages.VideoFocusRequest.focus_mode', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='focus_reason', full_name='gb.xxy.trial.proto.messages.VideoFocusRequest.focus_reason', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=295,
)

_VIDEOFOCUSREQUEST.fields_by_name['focus_mode'].enum_type = VideoFocusModeEnum__pb2._VIDEOFOCUSMODE_ENUM
_VIDEOFOCUSREQUEST.fields_by_name['focus_reason'].enum_type = VideoFocusReasonEnum__pb2._VIDEOFOCUSREASON_ENUM
DESCRIPTOR.message_types_by_name['VideoFocusRequest'] = _VIDEOFOCUSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFocusRequest = _reflection.GeneratedProtocolMessageType('VideoFocusRequest', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOFOCUSREQUEST,
  '__module__' : 'VideoFocusRequestMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.VideoFocusRequest)
  })
_sym_db.RegisterMessage(VideoFocusRequest)


# @@protoc_insertion_point(module_scope)
