# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VideoFPSEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VideoFPSEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12VideoFPSEnum.proto\x12\x18gb.xxy.trial.proto.enums\".\n\x08VideoFPS\"\"\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03_30\x10\x01\x12\x07\n\x03_60\x10\x02')
)



_VIDEOFPS_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.VideoFPS.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='_30', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='_60', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=60,
  serialized_end=94,
)
_sym_db.RegisterEnumDescriptor(_VIDEOFPS_ENUM)


_VIDEOFPS = _descriptor.Descriptor(
  name='VideoFPS',
  full_name='gb.xxy.trial.proto.enums.VideoFPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIDEOFPS_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=94,
)

_VIDEOFPS_ENUM.containing_type = _VIDEOFPS
DESCRIPTOR.message_types_by_name['VideoFPS'] = _VIDEOFPS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFPS = _reflection.GeneratedProtocolMessageType('VideoFPS', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOFPS,
  '__module__' : 'VideoFPSEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.VideoFPS)
  })
_sym_db.RegisterMessage(VideoFPS)


# @@protoc_insertion_point(module_scope)
