# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VideoFocusIndicationMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import VideoFocusModeEnum_pb2 as VideoFocusModeEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='VideoFocusIndicationMessage.proto',
  package='gb.xxy.trial.proto.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n!VideoFocusIndicationMessage.proto\x12\x1bgb.xxy.trial.proto.messages\x1a\x18VideoFocusModeEnum.proto\"n\n\x14VideoFocusIndication\x12\x41\n\nfocus_mode\x18\x01 \x02(\x0e\x32-.gb.xxy.trial.proto.enums.VideoFocusMode.Enum\x12\x13\n\x0bunrequested\x18\x02 \x02(\x08')
  ,
  dependencies=[VideoFocusModeEnum__pb2.DESCRIPTOR,])




_VIDEOFOCUSINDICATION = _descriptor.Descriptor(
  name='VideoFocusIndication',
  full_name='gb.xxy.trial.proto.messages.VideoFocusIndication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='focus_mode', full_name='gb.xxy.trial.proto.messages.VideoFocusIndication.focus_mode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unrequested', full_name='gb.xxy.trial.proto.messages.VideoFocusIndication.unrequested', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=202,
)

_VIDEOFOCUSINDICATION.fields_by_name['focus_mode'].enum_type = VideoFocusModeEnum__pb2._VIDEOFOCUSMODE_ENUM
DESCRIPTOR.message_types_by_name['VideoFocusIndication'] = _VIDEOFOCUSINDICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFocusIndication = _reflection.GeneratedProtocolMessageType('VideoFocusIndication', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOFOCUSINDICATION,
  '__module__' : 'VideoFocusIndicationMessage_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.messages.VideoFocusIndication)
  })
_sym_db.RegisterMessage(VideoFocusIndication)


# @@protoc_insertion_point(module_scope)
