# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VideoResolutionEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VideoResolutionEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19VideoResolutionEnum.proto\x12\x18gb.xxy.trial.proto.enums\"E\n\x0fVideoResolution\"2\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05_480p\x10\x01\x12\t\n\x05_720p\x10\x02\x12\n\n\x06_1080p\x10\x03')
)



_VIDEORESOLUTION_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.VideoResolution.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='_480p', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='_720p', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='_1080p', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=74,
  serialized_end=124,
)
_sym_db.RegisterEnumDescriptor(_VIDEORESOLUTION_ENUM)


_VIDEORESOLUTION = _descriptor.Descriptor(
  name='VideoResolution',
  full_name='gb.xxy.trial.proto.enums.VideoResolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIDEORESOLUTION_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=124,
)

_VIDEORESOLUTION_ENUM.containing_type = _VIDEORESOLUTION
DESCRIPTOR.message_types_by_name['VideoResolution'] = _VIDEORESOLUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoResolution = _reflection.GeneratedProtocolMessageType('VideoResolution', (_message.Message,), {
  'DESCRIPTOR' : _VIDEORESOLUTION,
  '__module__' : 'VideoResolutionEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.VideoResolution)
  })
_sym_db.RegisterMessage(VideoResolution)


# @@protoc_insertion_point(module_scope)
