# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VideoFocusReasonEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VideoFocusReasonEnum.proto',
  package='gb.xxy.trial.proto.enums',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1aVideoFocusReasonEnum.proto\x12\x18gb.xxy.trial.proto.enums\":\n\x10VideoFocusReason\"&\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05UNK_1\x10\x01\x12\t\n\x05UNK_2\x10\x02')
)



_VIDEOFOCUSREASON_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='gb.xxy.trial.proto.enums.VideoFocusReason.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNK_1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNK_2', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=76,
  serialized_end=114,
)
_sym_db.RegisterEnumDescriptor(_VIDEOFOCUSREASON_ENUM)


_VIDEOFOCUSREASON = _descriptor.Descriptor(
  name='VideoFocusReason',
  full_name='gb.xxy.trial.proto.enums.VideoFocusReason',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIDEOFOCUSREASON_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=114,
)

_VIDEOFOCUSREASON_ENUM.containing_type = _VIDEOFOCUSREASON
DESCRIPTOR.message_types_by_name['VideoFocusReason'] = _VIDEOFOCUSREASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFocusReason = _reflection.GeneratedProtocolMessageType('VideoFocusReason', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOFOCUSREASON,
  '__module__' : 'VideoFocusReasonEnum_pb2'
  # @@protoc_insertion_point(class_scope:gb.xxy.trial.proto.enums.VideoFocusReason)
  })
_sym_db.RegisterMessage(VideoFocusReason)


# @@protoc_insertion_point(module_scope)
